# Travis config for S8080
# 
# Stefan Wong 8080

language: c
sudo: true
compiler: gcc
dist: bionic

before_install:
    - travis_retry curl -L https://www.libsdl.org/release/SDL2-2.0.8.tar.gz | tar xz
    - cd SDL2-2.0.8
    - ./configure
    - make
    - sudo make install
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:SDL2-2.0.8/
    - cd ..

script: 
    - make clean && make all
    - ./test/run_tests.sh
